### ISSUE TITLE
Q princeton university about computer science after 2010

### ISSUE THREAD

**Issue by arnabsinha83** [arnabsinha83/TestAcademicAPI#3]
This should return some result. I know it is not working since there are more than one predicates in the query. But it is valid. Our constraint should be relaxed.

**Comment by jayantacs** [comment]
This is an ambiguous query, at this point we can only, ask clarification for author-based ambiguation.

**Comment by jayanta-mondal** [comment]
Interpret method doesn't return any predicate for this query.

**Comment by arnabsinha83** [comment]
Fixed.
