### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by arnabsinha83** [arnabsinha83/TestAcademicAPI#6]
I type papers by Einstein, I got 5 results, I choose 5.
a.  When I choose 4 again, I get internal server error – The bug would be – user must be able to traverse to other items in the query.

**Comment by jayanta-mondal** [comment]
fixed

**Comment by arnabsinha83** [comment]
I don't like this fix. It basically terminates the conversation by force. The user might be still interested in the old conversation.

**Comment by arnabsinha83** [comment]
![image](https://cloud.githubusercontent.com/assets/8241706/17150597/e4aa0a52-5324-11e6-90b0-37b76b7d97e5.png)
