### ISSUE TITLE
every conversation must end with a link to academic page with the original query

### ISSUE THREAD

**Issue by sundaradinakar** [arnabsinha83/TestAcademicAPI#8]
From: Arnab Sinha 
## I like this idea.

From: Sundara Pasupathi 
Cool Arnab – what we can do for #2 is –  
put a link at the end of every message (give him the query link) that takes to the academic search page with his query –  that way he does not feel random / incomplete result given to him.

**Comment by arnabsinha83** [comment]
It is already there for unambiguous queries. It is difficult for ambiguous ones as I don't have the natural language query after there is a clarification question.

**Comment by arnabsinha83** [comment]
Added for all types of queries.
