### ISSUE TITLE
bot needs to be fine tuned (complains of ambiguity in simple queries)

### ISSUE THREAD

**Issue by sundaradinakar** [arnabsinha83/TestAcademicAPI#9]
Scenarios:
1.  **Q Albert Einstein –> system gives 2 results, select 1 –> failure message (bug)**
2.  Q Arnab Sinha -> gives good results (great!)
3.  Q papers written by arnab Sinha -> gives good results (great!)
4.  Q papers written by Sundara -> system gives 5 results -> select 1 -> good output (great!)
5.  **Q papers Einstein -> complains about ambiguity**
6.  Q papers Robert Einstein -> good results (great!)
7.  **Q papers by Robert Einstein in 2004 -> sorry did not return results (we need to add disambiguation)**
8.  **Q papers written by albert Einstein -> pick one to proceed -> 1 -> good results (great!) -> 2 ( sorry message)**
9.  **Q papers by albert Einstein in 2008 -> sorry message (need to add disambiguation)**
10. Q papers Einstein 2008 -> 1 -> results (good!)

I ran like 10 scenarios above – around 4 issues found

**Comment by arnabsinha83** [comment]
Issue 7. Nothing can be done since there is no matching result for that query.

**Comment by jayanta-mondal** [comment]
1. Fixed
2. Interpret method returns null
3. Fixed
4. Fixed

**Comment by arnabsinha83** [comment]
1. By design. You give a choice and the conversation ends there.
   7,9. Issues with underlying Academic API.
